name: マージ後ブランチ自動削除

on:
  pull_request:
    types:
      - closed

permissions:
    contents: write

jobs:
  delete-merged-branch:
    runs-on: ubuntu-latest
    env:
        # マージ後も削除しないブランチをスペース区切りで指定する
        SKIP_BRANCHES: "develop anydoc/update"

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Delete Merged Branch
      run: |
        MERGED_BRANCH_NAME=$(echo "${{ github.event.pull_request.head.ref }}" | tr -d '\n')
        if [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.event.action }}" == "closed" ] && [ "${{ github.event.pull_request.merged }}" == "true" && "$SKIP_BRANCHES" =~ (^| )"$MERGED_BRANCH_NAME"($| ) ]]; then
          git push origin --delete "$MERGED_BRANCH_NAME"
          echo "Merged branch '$MERGED_BRANCH_NAME' deleted."
        else
          echo "No branch to delete."
        fi