name: マージ後ブランチ自動削除

on:
  pull_request:
    types:
      - closed

permissions:
    contents: write

jobs:
  delete-merged-branch:
    runs-on: ubuntu-latest
    env:
        BASE_BRANCH: "main"

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Delete Merged Branch
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.event.action }}" == "closed" ] && [ "${{ github.event.pull_request.merged }}" == "true" ] && [ "${{ github.event.pull_request.base.ref }}" == "$BASE_BRANCH" ]; then
          mergedBranchName=$(echo "${{ github.event.pull_request.head.ref }}" | tr -d '\n')
          git push origin --delete "$mergedBranchName"
          echo "Merged branch '$mergedBranchName' deleted."
        else
          echo "Not a merged pull request to the $BASE_BRANCH branch. Skipping."
        fi