name: プルリク時自動整形

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: write

jobs:
  format-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    - name: Install gofumpt
      run: go install mvdan.cc/gofumpt@latest

    - name: Format Code
      run: gofumpt -l -w -extra .
    # コミットするのはアクションユーザーにしています。
    - name: Commit Changes
      run: |
        if ! git diff --exit-code --quiet
        then
          git config user.name GitHub Action
          git config user.email action@github.com
          git add .
          git commit -m "Format code using gofumpt"
          git push
        fi